
import Debts.Debt;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Himanshu Soni
 */
public class Soni_Dept extends javax.swing.JFrame {

    /**
     * Creates new form Soni_Dept
     */
    Connection con;

    public Soni_Dept() {
        initComponents();
        jButton1.setFocusable(false);
        cust_bill.setFocusable(false);
        shop_bill.setFocusable(false);
        jButton4.setFocusable(false);
        jButton2.setFocusable(false);
        jButton3.setFocusable(false);
        debt.setFocusable(false);
        rough.setFocusable(false);
    }

    public Soni_Dept(Connection conn) {
        this();
        con = conn;
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cust_bill = new javax.swing.JButton();
        shop_bill = new javax.swing.JButton();
        debt = new javax.swing.JButton();
        rough = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        rough1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Departmental Store Software");
        setMinimumSize(new java.awt.Dimension(400, 310));
        getContentPane().setLayout(null);

        cust_bill.setText("Sale");
        cust_bill.setToolTipText("");
        cust_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cust_billActionPerformed(evt);
            }
        });
        getContentPane().add(cust_bill);
        cust_bill.setBounds(10, 10, 140, 23);

        shop_bill.setText("Purchase");
        shop_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shop_billActionPerformed(evt);
            }
        });
        getContentPane().add(shop_bill);
        shop_bill.setBounds(10, 90, 140, 23);

        debt.setText("Acc. Statement");
        debt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debtActionPerformed(evt);
            }
        });
        getContentPane().add(debt);
        debt.setBounds(10, 170, 140, 23);

        rough.setText("Stock");
        rough.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roughActionPerformed(evt);
            }
        });
        getContentPane().add(rough);
        rough.setBounds(270, 130, 100, 23);

        jButton1.setText("Add / Remove Item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 130, 140, 23);

        jButton2.setText("Open File");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(270, 30, 90, 23);

        jButton3.setText("Delete File");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(270, 80, 100, 23);

        jButton4.setText("Receipt");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(10, 50, 140, 23);

        rough1.setText("Rough Notebook");
        rough1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rough1ActionPerformed(evt);
            }
        });
        getContentPane().add(rough1);
        rough1.setBounds(10, 210, 140, 23);

        jButton5.setText("Backup");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(270, 180, 100, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -170, 400, 610);

        jMenu3.setText("File");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem4.setText("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Settings");

        jMenuItem3.setText("Change Password");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar2.add(jMenu4);

        jMenu1.setText("Help");

        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar2.add(jMenu1);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cust_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cust_billActionPerformed
        CustomerBill.Add_Bill cust = new CustomerBill.Add_Bill(con);
        cust.setVisible(true);

    }//GEN-LAST:event_cust_billActionPerformed

    private void shop_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shop_billActionPerformed
        ShopkeeperBill.Add shop = new ShopkeeperBill.Add(con);
        shop.setVisible(true);
    }//GEN-LAST:event_shop_billActionPerformed

    private void debtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debtActionPerformed
        Debt debtt = new Debt(con);
        debtt.setVisible(true);
    }//GEN-LAST:event_debtActionPerformed

    private void roughActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roughActionPerformed
        Stock.Stock roug = new Stock.Stock(con);
        roug.setVisible(true);
    }//GEN-LAST:event_roughActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Item list = new Item(con);
        list.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        changepass p = new changepass(con);
        p.setVisible(true);
        //dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        about a = new about();
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Process p = Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler d:/result.xls");
            p.waitFor();
            System.out.println("Done.");
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        File file = new File("d:\\result.xls");
        file.delete();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Debts.Customer_cash c = new Debts.Customer_cash(con);
        c.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void rough1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rough1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rough1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            Date dt = new Date();
            String md = new SimpleDateFormat("dd-MMM-yyyy").format(dt);
            File f = new File("d:\\run.bat");
            if (f.exists()) {
                f.delete();
            }
            f.createNewFile();
            FileWriter fw = new FileWriter(f.getAbsoluteFile());
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write("mysqldump -u root -p hsoni > D:/" + md + ".sql");
            bw.close();
            Runtime.getRuntime().exec("cmd.exe /c start runit.bat");

        } catch (IOException ex) {
            Logger.getLogger(Soni_Dept.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Soni_Dept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Soni_Dept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Soni_Dept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Soni_Dept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Soni_Dept().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cust_bill;
    private javax.swing.JButton debt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JButton rough;
    private javax.swing.JButton rough1;
    private javax.swing.JButton shop_bill;
    // End of variables declaration//GEN-END:variables
}
